id: P010595
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16147
  title: ཟུར་བཀོལ་བཞིའི་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན།
  author: ''
  volumes:
    96570dbb89bd4aab8b22151bd78c2286:
      image_group_id: I1KG16151
      title: ''
      volume_number: 1
      total_pages: 604
