id: IE7CC29F7
legacy_id: P010595
ocr_import_info:
  bdrc_scan_id: W1KG16147
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:09:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:29:21.834742+00:00'
last_modified: 2022-08-31 16:29:39.462848
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16147
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16147
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟུར་བཀོལ་བཞིའི་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན།
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9397621125635305
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG16151:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16151
      total_pages: 604
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16151.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9397621125635305
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
